#!/bin/sh

case "$1" in
start)
	mkdir -p /etc/crontabs
	crond -c /etc/crontabs
	;;
stop)
	killall crond 2>/dev/null
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
