#!/bin/sh

REDIS_CONF=/etc/redis/redis.conf
PIDFILE=/var/run/redis.pid

case "$1" in
start)
	[ -f "$REDIS_CONF" ] || exit 0
	mkdir -p /data/redis
	printf "Starting redis: "
	start-stop-daemon -S -q -b -m -p "$PIDFILE" -x /usr/bin/redis-server -- \
		"$REDIS_CONF"
	taskset -cp 0,1 "$(cat "$PIDFILE")" 2>/dev/null || true
	echo "OK"
	;;
stop)
	printf "Stopping redis: "
	start-stop-daemon -K -q -p "$PIDFILE" 2>/dev/null
	echo "OK"
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
