#!/bin/sh

DAEMON=/usr/sbin/fanctl
PIDFILE=/var/run/fanctl.pid

case "$1" in
start)
	[ -x "$DAEMON" ] || exit 0
	printf "Starting fanctl: "
	start-stop-daemon -S -q -b -m -p "$PIDFILE" -x "$DAEMON" -- daemon
	echo "OK"
	;;
stop)
	printf "Stopping fanctl: "
	start-stop-daemon -K -q -p "$PIDFILE" 2>/dev/null
	$DAEMON stop 2>/dev/null
	echo "OK"
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
