#!/bin/sh

case "$1" in
start)
	printf "Starting dropbear: "
	/usr/sbin/dropbear -R
	echo "OK"
	;;
stop)
	printf "Stopping dropbear: "
	killall dropbear 2>/dev/null
	echo "OK"
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac
